# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.jtsk import Jtsk  # noqa: F401,E501
from swagger_server.models.wgs import Wgs  # noqa: F401,E501
from swagger_server import util


class Coordinates(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, jtsk: Jtsk = None, wgs: Wgs = None):  # noqa: E501
        """Coordinates - a model defined in Swagger

        :param jtsk: The jtsk of this Coordinates.  # noqa: E501
        :type jtsk: Jtsk
        :param wgs: The wgs of this Coordinates.  # noqa: E501
        :type wgs: Wgs
        """
        self.swagger_types = {
            'jtsk': Jtsk,
            'wgs': Wgs
        }

        self.attribute_map = {
            'jtsk': 'jtsk',
            'wgs': 'wgs'
        }
        self._jtsk = jtsk
        self._wgs = wgs

    @classmethod
    def from_dict(cls, dikt) -> 'Coordinates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coordinates of this Coordinates.  # noqa: E501
        :rtype: Coordinates
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jtsk(self) -> Jtsk:
        """Gets the jtsk of this Coordinates.


        :return: The jtsk of this Coordinates.
        :rtype: Jtsk
        """
        return self._jtsk

    @jtsk.setter
    def jtsk(self, jtsk: Jtsk):
        """Sets the jtsk of this Coordinates.


        :param jtsk: The jtsk of this Coordinates.
        :type jtsk: Jtsk
        """

        self._jtsk = jtsk

    @property
    def wgs(self) -> Wgs:
        """Gets the wgs of this Coordinates.


        :return: The wgs of this Coordinates.
        :rtype: Wgs
        """
        return self._wgs

    @wgs.setter
    def wgs(self, wgs: Wgs):
        """Sets the wgs of this Coordinates.


        :param wgs: The wgs of this Coordinates.
        :type wgs: Wgs
        """

        self._wgs = wgs
