# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.address import Address  # noqa: F401,E501
from swagger_server.models.administrative_division import AdministrativeDivision  # noqa: F401,E501
from swagger_server.models.mapovy_list50 import MapovyList50  # noqa: F401,E501
from swagger_server.models.povodi import Povodi  # noqa: F401,E501
from swagger_server import util


class FullAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address_point: Address=None, administrative_division: AdministrativeDivision=None, basin: Povodi=None, map50_sheet: MapovyList50=None):  # noqa: E501
        """FullAddress - a model defined in Swagger

        :param address_point: The address_point of this FullAddress.  # noqa: E501
        :type address_point: Address
        :param administrative_division: The administrative_division of this FullAddress.  # noqa: E501
        :type administrative_division: AdministrativeDivision
        :param basin: The basin of this FullAddress.  # noqa: E501
        :type basin: Povodi
        :param map50_sheet: The map50_sheet of this FullAddress.  # noqa: E501
        :type map50_sheet: MapovyList50
        """
        self.swagger_types = {
            'address_point': Address,
            'administrative_division': AdministrativeDivision,
            'basin': Povodi,
            'map50_sheet': MapovyList50
        }

        self.attribute_map = {
            'address_point': 'address_point',
            'administrative_division': 'administrative_division',
            'basin': 'basin',
            'map50_sheet': 'map50_sheet'
        }
        self._address_point = address_point
        self._administrative_division = administrative_division
        self._basin = basin
        self._map50_sheet = map50_sheet

    @classmethod
    def from_dict(cls, dikt) -> 'FullAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FullAddress of this FullAddress.  # noqa: E501
        :rtype: FullAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address_point(self) -> Address:
        """Gets the address_point of this FullAddress.


        :return: The address_point of this FullAddress.
        :rtype: Address
        """
        return self._address_point

    @address_point.setter
    def address_point(self, address_point: Address):
        """Sets the address_point of this FullAddress.


        :param address_point: The address_point of this FullAddress.
        :type address_point: Address
        """

        self._address_point = address_point

    @property
    def administrative_division(self) -> AdministrativeDivision:
        """Gets the administrative_division of this FullAddress.


        :return: The administrative_division of this FullAddress.
        :rtype: AdministrativeDivision
        """
        return self._administrative_division

    @administrative_division.setter
    def administrative_division(self, administrative_division: AdministrativeDivision):
        """Sets the administrative_division of this FullAddress.


        :param administrative_division: The administrative_division of this FullAddress.
        :type administrative_division: AdministrativeDivision
        """

        self._administrative_division = administrative_division

    @property
    def basin(self) -> Povodi:
        """Gets the basin of this FullAddress.


        :return: The basin of this FullAddress.
        :rtype: Povodi
        """
        return self._basin

    @basin.setter
    def basin(self, basin: Povodi):
        """Sets the basin of this FullAddress.


        :param basin: The basin of this FullAddress.
        :type basin: Povodi
        """

        self._basin = basin

    @property
    def map50_sheet(self) -> MapovyList50:
        """Gets the map50_sheet of this FullAddress.


        :return: The map50_sheet of this FullAddress.
        :rtype: MapovyList50
        """
        return self._map50_sheet

    @map50_sheet.setter
    def map50_sheet(self, map50_sheet: MapovyList50):
        """Sets the map50_sheet of this FullAddress.


        :param map50_sheet: The map50_sheet of this FullAddress.
        :type map50_sheet: MapovyList50
        """

        self._map50_sheet = map50_sheet
