# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MapovyList50(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id_value: str = None, nazev: str = None):  # noqa: E501
        """MapovyList50 - a model defined in Swagger

        :param id_value: The id of this MapovyList50.  # noqa: E501
        :type id_value: str
        :param nazev: The nazev of this MapovyList50.  # noqa: E501
        :type nazev: str
        """
        self.swagger_types = {
            'id': str,
            'nazev': str
        }

        self.attribute_map = {
            'id': 'id',
            'nazev': 'nazev'
        }
        self._id = id_value
        self._nazev = nazev

    @classmethod
    def from_dict(cls, dikt) -> 'MapovyList50':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MapovyList50 of this MapovyList50.  # noqa: E501
        :rtype: MapovyList50
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this MapovyList50.


        :return: The id of this MapovyList50.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id_value: str):
        """Sets the id of this MapovyList50.


        :param id_value: The id of this MapovyList50.
        :type id_value: str
        """

        self._id = id_value

    @property
    def nazev(self) -> str:
        """Gets the nazev of this MapovyList50.


        :return: The nazev of this MapovyList50.
        :rtype: str
        """
        return self._nazev

    @nazev.setter
    def nazev(self, nazev: str):
        """Sets the nazev of this MapovyList50.


        :param nazev: The nazev of this MapovyList50.
        :type nazev: str
        """

        self._nazev = nazev
