# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.point_wgs import PointWgs  # noqa: F401,E501
from swagger_server import util


class PolygonWgs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, polygon: List[PointWgs]=None):  # noqa: E501
        """PolygonWgs - a model defined in Swagger

        :param polygon: The polygon of this PolygonWgs.  # noqa: E501
        :type polygon: List[PointWgs]
        """
        self.swagger_types = {
            'polygon': List[PointWgs]
        }

        self.attribute_map = {
            'polygon': 'polygon'
        }
        self._polygon = polygon

    @classmethod
    def from_dict(cls, dikt) -> 'PolygonWgs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PolygonWgs of this PolygonWgs.  # noqa: E501
        :rtype: PolygonWgs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def polygon(self) -> List[PointWgs]:
        """Gets the polygon of this PolygonWgs.


        :return: The polygon of this PolygonWgs.
        :rtype: List[PointWgs]
        """
        return self._polygon

    @polygon.setter
    def polygon(self, polygon: List[PointWgs]):
        """Sets the polygon of this PolygonWgs.


        :param polygon: The polygon of this PolygonWgs.
        :type polygon: List[PointWgs]
        """

        self._polygon = polygon
