# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Povodi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_1: int=None, id_2: int=None, id_3: int=None, chp: str=None, chp_d: str=None, chp_u: str=None, naz_pov_1: str=None, naz_pov_2: str=None, naz_pov_3: str=None, naz_tok: str=None, naz_tok_2: str=None):  # noqa: E501
        """Povodi - a model defined in Swagger

        :param id: The id of this Povodi.  # noqa: E501
        :type id: int
        :param id_1: The id_1 of this Povodi.  # noqa: E501
        :type id_1: int
        :param id_2: The id_2 of this Povodi.  # noqa: E501
        :type id_2: int
        :param id_3: The id_3 of this Povodi.  # noqa: E501
        :type id_3: int
        :param chp: The chp of this Povodi.  # noqa: E501
        :type chp: str
        :param chp_d: The chp_d of this Povodi.  # noqa: E501
        :type chp_d: str
        :param chp_u: The chp_u of this Povodi.  # noqa: E501
        :type chp_u: str
        :param naz_pov_1: The naz_pov_1 of this Povodi.  # noqa: E501
        :type naz_pov_1: str
        :param naz_pov_2: The naz_pov_2 of this Povodi.  # noqa: E501
        :type naz_pov_2: str
        :param naz_pov_3: The naz_pov_3 of this Povodi.  # noqa: E501
        :type naz_pov_3: str
        :param naz_tok: The naz_tok of this Povodi.  # noqa: E501
        :type naz_tok: str
        :param naz_tok_2: The naz_tok_2 of this Povodi.  # noqa: E501
        :type naz_tok_2: str
        """
        self.swagger_types = {
            'id': int,
            'id_1': int,
            'id_2': int,
            'id_3': int,
            'chp': str,
            'chp_d': str,
            'chp_u': str,
            'naz_pov_1': str,
            'naz_pov_2': str,
            'naz_pov_3': str,
            'naz_tok': str,
            'naz_tok_2': str
        }

        self.attribute_map = {
            'id': 'id',
            'id_1': 'id_1',
            'id_2': 'id_2',
            'id_3': 'id_3',
            'chp': 'chp',
            'chp_d': 'chp_d',
            'chp_u': 'chp_u',
            'naz_pov_1': 'naz_pov_1',
            'naz_pov_2': 'naz_pov_2',
            'naz_pov_3': 'naz_pov_3',
            'naz_tok': 'naz_tok',
            'naz_tok_2': 'naz_tok_2'
        }
        self._id = id
        self._id_1 = id_1
        self._id_2 = id_2
        self._id_3 = id_3
        self._chp = chp
        self._chp_d = chp_d
        self._chp_u = chp_u
        self._naz_pov_1 = naz_pov_1
        self._naz_pov_2 = naz_pov_2
        self._naz_pov_3 = naz_pov_3
        self._naz_tok = naz_tok
        self._naz_tok_2 = naz_tok_2

    @classmethod
    def from_dict(cls, dikt) -> 'Povodi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Povodi of this Povodi.  # noqa: E501
        :rtype: Povodi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Povodi.


        :return: The id of this Povodi.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Povodi.


        :param id: The id of this Povodi.
        :type id: int
        """

        self._id = id

    @property
    def id_1(self) -> int:
        """Gets the id_1 of this Povodi.


        :return: The id_1 of this Povodi.
        :rtype: int
        """
        return self._id_1

    @id_1.setter
    def id_1(self, id_1: int):
        """Sets the id_1 of this Povodi.


        :param id_1: The id_1 of this Povodi.
        :type id_1: int
        """

        self._id_1 = id_1

    @property
    def id_2(self) -> int:
        """Gets the id_2 of this Povodi.


        :return: The id_2 of this Povodi.
        :rtype: int
        """
        return self._id_2

    @id_2.setter
    def id_2(self, id_2: int):
        """Sets the id_2 of this Povodi.


        :param id_2: The id_2 of this Povodi.
        :type id_2: int
        """

        self._id_2 = id_2

    @property
    def id_3(self) -> int:
        """Gets the id_3 of this Povodi.


        :return: The id_3 of this Povodi.
        :rtype: int
        """
        return self._id_3

    @id_3.setter
    def id_3(self, id_3: int):
        """Sets the id_3 of this Povodi.


        :param id_3: The id_3 of this Povodi.
        :type id_3: int
        """

        self._id_3 = id_3

    @property
    def chp(self) -> str:
        """Gets the chp of this Povodi.


        :return: The chp of this Povodi.
        :rtype: str
        """
        return self._chp

    @chp.setter
    def chp(self, chp: str):
        """Sets the chp of this Povodi.


        :param chp: The chp of this Povodi.
        :type chp: str
        """

        self._chp = chp

    @property
    def chp_d(self) -> str:
        """Gets the chp_d of this Povodi.


        :return: The chp_d of this Povodi.
        :rtype: str
        """
        return self._chp_d

    @chp_d.setter
    def chp_d(self, chp_d: str):
        """Sets the chp_d of this Povodi.


        :param chp_d: The chp_d of this Povodi.
        :type chp_d: str
        """

        self._chp_d = chp_d

    @property
    def chp_u(self) -> str:
        """Gets the chp_u of this Povodi.


        :return: The chp_u of this Povodi.
        :rtype: str
        """
        return self._chp_u

    @chp_u.setter
    def chp_u(self, chp_u: str):
        """Sets the chp_u of this Povodi.


        :param chp_u: The chp_u of this Povodi.
        :type chp_u: str
        """

        self._chp_u = chp_u

    @property
    def naz_pov_1(self) -> str:
        """Gets the naz_pov_1 of this Povodi.


        :return: The naz_pov_1 of this Povodi.
        :rtype: str
        """
        return self._naz_pov_1

    @naz_pov_1.setter
    def naz_pov_1(self, naz_pov_1: str):
        """Sets the naz_pov_1 of this Povodi.


        :param naz_pov_1: The naz_pov_1 of this Povodi.
        :type naz_pov_1: str
        """

        self._naz_pov_1 = naz_pov_1

    @property
    def naz_pov_2(self) -> str:
        """Gets the naz_pov_2 of this Povodi.


        :return: The naz_pov_2 of this Povodi.
        :rtype: str
        """
        return self._naz_pov_2

    @naz_pov_2.setter
    def naz_pov_2(self, naz_pov_2: str):
        """Sets the naz_pov_2 of this Povodi.


        :param naz_pov_2: The naz_pov_2 of this Povodi.
        :type naz_pov_2: str
        """

        self._naz_pov_2 = naz_pov_2

    @property
    def naz_pov_3(self) -> str:
        """Gets the naz_pov_3 of this Povodi.


        :return: The naz_pov_3 of this Povodi.
        :rtype: str
        """
        return self._naz_pov_3

    @naz_pov_3.setter
    def naz_pov_3(self, naz_pov_3: str):
        """Sets the naz_pov_3 of this Povodi.


        :param naz_pov_3: The naz_pov_3 of this Povodi.
        :type naz_pov_3: str
        """

        self._naz_pov_3 = naz_pov_3

    @property
    def naz_tok(self) -> str:
        """Gets the naz_tok of this Povodi.


        :return: The naz_tok of this Povodi.
        :rtype: str
        """
        return self._naz_tok

    @naz_tok.setter
    def naz_tok(self, naz_tok: str):
        """Sets the naz_tok of this Povodi.


        :param naz_tok: The naz_tok of this Povodi.
        :type naz_tok: str
        """

        self._naz_tok = naz_tok

    @property
    def naz_tok_2(self) -> str:
        """Gets the naz_tok_2 of this Povodi.


        :return: The naz_tok_2 of this Povodi.
        :rtype: str
        """
        return self._naz_tok_2

    @naz_tok_2.setter
    def naz_tok_2(self, naz_tok_2: str):
        """Sets the naz_tok_2 of this Povodi.


        :param naz_tok_2: The naz_tok_2 of this Povodi.
        :type naz_tok_2: str
        """

        self._naz_tok_2 = naz_tok_2
