# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Wgs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, lat: str=None, lon: str=None):  # noqa: E501
        """Wgs - a model defined in Swagger

        :param lat: The lat of this Wgs.  # noqa: E501
        :type lat: str
        :param lon: The lon of this Wgs.  # noqa: E501
        :type lon: str
        """
        self.swagger_types = {
            'lat': str,
            'lon': str
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon'
        }
        self._lat = lat
        self._lon = lon

    @classmethod
    def from_dict(cls, dikt) -> 'Wgs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Wgs of this Wgs.  # noqa: E501
        :rtype: Wgs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> str:
        """Gets the lat of this Wgs.


        :return: The lat of this Wgs.
        :rtype: str
        """
        return self._lat

    @lat.setter
    def lat(self, lat: str):
        """Sets the lat of this Wgs.


        :param lat: The lat of this Wgs.
        :type lat: str
        """

        self._lat = lat

    @property
    def lon(self) -> str:
        """Gets the lon of this Wgs.


        :return: The lon of this Wgs.
        :rtype: str
        """
        return self._lon

    @lon.setter
    def lon(self, lon: str):
        """Sets the lon of this Wgs.


        :param lon: The lon of this Wgs.
        :type lon: str
        """

        self._lon = lon
