# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.administrative_division import AdministrativeDivision  # noqa: F401,E501
from swagger_server import util


class Zsj(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id_value: int = None, nazev: str = None,
                 administrative_division: AdministrativeDivision = None):  # noqa: E501
        """Zsj - a model defined in Swagger

        :param id_value: The id of this Zsj.  # noqa: E501
        :type id_value: int
        :param nazev: The nazev of this Zsj.  # noqa: E501
        :type nazev: str
        :param administrative_division: The administrative_division of this Zsj.  # noqa: E501
        :type administrative_division: AdministrativeDivision
        """
        self.swagger_types = {
            'id': int,
            'nazev': str,
            'administrative_division': AdministrativeDivision
        }

        self.attribute_map = {
            'id': 'id',
            'nazev': 'nazev',
            'administrative_division': 'administrative_division'
        }
        self._id = id_value
        self._nazev = nazev
        self._administrative_division = administrative_division

    @classmethod
    def from_dict(cls, dikt) -> 'Zsj':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Zsj of this Zsj.  # noqa: E501
        :rtype: Zsj
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Zsj.


        :return: The id of this Zsj.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id_value: int):
        """Sets the id of this Zsj.


        :param id_value: The id of this Zsj.
        :type id_value: int
        """

        self._id = id_value

    @property
    def nazev(self) -> str:
        """Gets the nazev of this Zsj.


        :return: The nazev of this Zsj.
        :rtype: str
        """
        return self._nazev

    @nazev.setter
    def nazev(self, nazev: str):
        """Sets the nazev of this Zsj.


        :param nazev: The nazev of this Zsj.
        :type nazev: str
        """

        self._nazev = nazev

    @property
    def administrative_division(self) -> AdministrativeDivision:
        """Gets the administrative_division of this Zsj.


        :return: The administrative_division of this Zsj.
        :rtype: AdministrativeDivision
        """
        return self._administrative_division

    @administrative_division.setter
    def administrative_division(self, administrative_division: AdministrativeDivision):
        """Sets the administrative_division of this Zsj.


        :param administrative_division: The administrative_division of this Zsj.
        :type administrative_division: AdministrativeDivision
        """

        self._administrative_division = administrative_division
